//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autor : IEquatable<Autor>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autor()
        {
            this.Libros = new HashSet<Libro>();
        }

        public Autor(string descripcion) // TODO No carga la tabla
        {
            Descripcion = descripcion;
        }

        public int IdAutor { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Libro> Libros { get; set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as Autor);
        }

        public bool Equals(Autor other)
        {
            return other != null &&
                   IdAutor == other.IdAutor;
        }

        public override int GetHashCode()
        {
            return -1644406393 + IdAutor.GetHashCode();
        }
    }
}
