//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lector : IEquatable<Lector>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lector()
        {
            this.Prestamos = new HashSet<Prestamo>();
        }

        public Lector(int numeroCarnet)
        {
            NumeroCarnet = numeroCarnet;
        }

        public Lector(int numeroCarnet, string nombre, string contrasena, string telefono, string mail)
        {
            NumeroCarnet = numeroCarnet;
            Nombre = nombre;
            Contrasena = contrasena;
            Telefono = telefono;
            Mail = mail;
        }

        public int NumeroCarnet { get; set; }
        public string Nombre { get; set; }
        public string Contrasena { get; set; }
        public string Telefono { get; set; }
        public string Mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamos { get; set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as Lector);
        }

        public bool Equals(Lector other)
        {
            return other != null &&
                   NumeroCarnet == other.NumeroCarnet;
        }

        public override int GetHashCode()
        {
            return -1830482804 + NumeroCarnet.GetHashCode();
        }
    }
}
