//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro : IEquatable<Libro>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.Prestamos = new HashSet<Prestamo>();
            this.Autores = new HashSet<Autor>();
            this.Categorias = new HashSet<Categoria>();
        }

        public Libro(int isbn)
        {
            Isbn = isbn;
        }

        public Libro(int isbn, string titulo, string editorial, string sipnosis, string caratula, int unidades, int numPrestado, bool disponibilidad)
        {
            Isbn = isbn;
            Titulo = titulo;
            Editorial = editorial;
            Sipnosis = sipnosis;
            Caratula = caratula;
            Unidades = unidades;
            NumPrestado = numPrestado;
            Disponibilidad = disponibilidad;
        }
        //Revisar
        public Libro(int isbn, string titulo, string editorial, string sipnosis, string caratula, int unidades, int numPrestado, bool disponibilidad,ICollection<Autor> autores, ICollection<Categoria> categorias) : this(isbn, titulo, editorial, sipnosis, caratula, unidades, numPrestado, disponibilidad)
        {
            Autores = autores;
            Categorias = categorias;
        }

        public int Isbn { get; set; }
        public string Titulo { get; set; }
        public string Editorial { get; set; }
        public string Sipnosis { get; set; }
        public string Caratula { get; set; }
        public int Unidades { get; set; }
        public int NumPrestado { get; set; }
        public bool Disponibilidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autor> Autores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categoria> Categorias { get; set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as Libro);
        }

        public bool Equals(Libro other)
        {
            return other != null &&
                   Isbn == other.Isbn;
        }

        public override int GetHashCode()
        {
            return 2140778025 + Isbn.GetHashCode();
        }
    }
}
