//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo : IEquatable<Prestamo>
    {
        private int isbn;
        private int numeroCarnet;

        public int IdLibro { get; set; }
        public int IdLector { get; set; }
        public System.DateTime FechaPrestado { get; set; }
        public System.DateTime FechaDevolucion { get; set; }

        public virtual Lector Lectores { get; set; }
        public virtual Libro Libro { get; set; }

        public Prestamo()
        {
        }

        public Prestamo(int idLibro, int idLector, DateTime fechaPrestado, DateTime fechaDevolucion)
        {
            IdLibro = idLibro;
            IdLector = idLector;
            FechaPrestado = fechaPrestado;
            FechaDevolucion = fechaDevolucion;
        }

        public Prestamo(int isbn, int numeroCarnet)
        {
            this.isbn = isbn;
            this.numeroCarnet = numeroCarnet;
        }

        public override bool Equals(object obj)
        {
            return Equals(obj as Prestamo);
        }

        public bool Equals(Prestamo other)
        {
            return other != null &&
                   IdLibro == other.IdLibro &&
                   IdLector == other.IdLector;
        }

        public override int GetHashCode()
        {
            var hashCode = 1463952393;
            hashCode = hashCode * -1521134295 + IdLibro.GetHashCode();
            hashCode = hashCode * -1521134295 + IdLector.GetHashCode();
            return hashCode;
        }
    }
}
