//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int IdLibro { get; set; }
        public int IdLector { get; set; }
        public System.DateTime FechaPrestado { get; set; }
        public System.DateTime FechaDevolucion { get; set; }

        public virtual Lector Lectores { get; set; }
        public virtual Libro Libro { get; set; }

        public Prestamo()
        {
        }

    }
}
